name: Compile Tailwind CSS

on:
  push:
    branches: 'main'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'tailwind/package-lock.json'


    - name: Compile Tailwind
      run: |
        cd ./tailwind
        npm ci
        bash compile.sh


    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: '[auto] Update Tailwind CSS'
        add: 'site/static/*.css'
